# Generated by Django 5.0.2 on 2024-11-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weeks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesocycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
                ('mesocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='wa.mesocycle')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(max_length=50)),
                ('exercise', models.CharField(max_length=255)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_exercises', to='wa.day')),
            ],
        ),
    ]
